version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5673:5672
      - 15672:15672

networks:
  webnet:
volumes:
  mongodb_data_container:
